name: Deploy to EC2
   
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t sgrobelny925/seb-personal.

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD  }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push sgrobelny925/seb-personal:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: prod
    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull sgrobelny925/seb-personal
            docker stop seb-blog || true
            docker rm seb-blog|| true
            docker run -d -p 3000:3000 --name seb-blog sgrobelny925/seb-personal