name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t sgrobelny925/seb-personal .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push sgrobelny925/seb-personal:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull sgrobelny925/seb-personal:latest
      - name: Delete old container
        run: docker rm -f seb-blog
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name seb-blog sgrobelny925/seb-personal