name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Add AWS Credentials Configuration
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Add AWS Credentials Check
      - name: Verify AWS Configuration
        run: |
          aws sts get-caller-identity || echo "AWS credentials not working"
          echo "AWS Region set to: ${{ secrets.AWS_REGION }}"

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Build
      - name: Build Next.js app
        run: npm run build

      # Add connection test before deployment
      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful"
            whoami
            pwd

      # Then proceed with your existing deployment steps
      - name: Transfer files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: ".next,package.json,package-lock.json,public,next.config.js"
          target: "/home/ubuntu/app"

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Ensure target directory exists and navigate to it
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app

            # Copy files from GitHub Actions runner to EC2
            # You might want to add rsync or scp step here to transfer the built files

            # Install dependencies and rebuild
            npm ci
            npm run build

            # Stop existing Next.js server if running (you may need to adjust this based on your process management)
            pkill -f "next start" || true

            # Start the Next.js server
            next start
