name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Add AWS Credentials Configuration
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Add AWS Credentials Check
      - name: Verify AWS Configuration
        run: |
          aws sts get-caller-identity || echo "AWS credentials not working"
          echo "AWS Region set to: ${{ secrets.AWS_REGION }}"

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Build
      - name: Build Next.js app
        run: npm run build

      # Step 5: Setup SSH with detailed debugging
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Starting SSH configuration..."
          echo "SSH_HOST value exists: $([[ -n $SSH_HOST ]] && echo 'Yes' || echo 'No')"
          echo "SSH_USER value exists: $([[ -n $SSH_USER ]] && echo 'Yes' || echo 'No')"
          echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"
          
          mkdir -p ~/.ssh
          echo "Created .ssh directory"
          
          # Write key with explicit newlines
          echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "Wrote private key to id_rsa"
          
          chmod 600 ~/.ssh/id_rsa
          echo "Set permissions on id_rsa"
          
          eval "$(ssh-agent -s)"
          echo "Started SSH agent"
          
          # Debug key format
          echo "Content of ~/.ssh directory:"
          ls -la ~/.ssh/
          
          echo "First few lines of SSH key (sanitized):"
          head -n 3 ~/.ssh/id_rsa | grep -E "BEGIN|END" || echo "No BEGIN/END markers found"
          
          # Add key to agent
          ssh-add ~/.ssh/id_rsa || echo "Failed to add SSH key"
          
          # Add host to known_hosts
          if [ -n "$SSH_HOST" ]; then
            echo "Adding host to known_hosts..."
            ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts 2>/dev/null
            echo "Added host to known_hosts"
          else
            echo "Error: EC2_HOST is empty"
            exit 1
          fi
          
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -vvv ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH test successful"' || echo "SSH connection failed"

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd /home/ubuntu/app
            git pull
            npm ci
            npm run build
            pm2 reload ecosystem.config.js --env production
          '
