name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Add AWS Credentials Configuration
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Add AWS Credentials Check
      - name: Verify AWS Configuration
        run: |
          aws sts get-caller-identity || echo "AWS credentials not working"
          echo "AWS Region set to: ${{ secrets.AWS_REGION }}"

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Build
      - name: Build Next.js app
        run: npm run build

      # Set up SSH for GitHub
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # Debug: Test GitHub SSH connection
          ssh -T git@github.com || true

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: GITHUB_TOKEN
          script: |
            # Debug: Show current user and permissions
            echo "Current user: $(whoami)"
            echo "Groups: $(groups)"
            echo "Working directory permissions:"
            ls -la /home/ubuntu/app
            cd /home/ubuntu/app
            
            # Configure git credentials
            git config --global credential.helper store
            echo "https://oauth2:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
            chmod 600 ~/.git-credentials
            
            # Configure git user
            git config --global user.email "sebastiangrobelny15@gmail.com"
            git config --global user.name "Sebastian Grobelny"
            git config --global --add safe.directory /home/ubuntu/app
            
            # Update remote URL with oauth2 format
            git remote remove origin
            git remote add origin "https://oauth2:${GITHUB_TOKEN}@github.com/SebastianG-Personal/seb-blog.git"
            
            # Debug: Show new remote (with token masked)
            echo "New remote configuration:"
            git remote -v | sed "s/${GITHUB_TOKEN}/***/"
            
            # Pull changes
            echo "Pulling changes..."
            git pull origin main
