name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Build
      - name: Build Next.js app
        run: npm run build

      # Step 4.5: Debug Environment Variables
      - name: Print Environment Variables
        run: |
          echo "Printing all environment variables:"
              printenv

      # Step 5: Setup SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "Key content (first and last lines):"
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | sed 's/\\n/\n/g' | tr -d '\r' | (head -n 1 && tail -n 1)
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | sed 's/\\n/\n/g' | tr -d '\r' > ~/.ssh/id_rsa
          echo "Key file content (first and last lines):"
          cat ~/.ssh/id_rsa | (head -n 1 && tail -n 1)
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd /home/ubuntu/app
            git pull
            npm ci
            npm run build
            pm2 reload ecosystem.config.js --env production
          '
